-- Create client_type data type
DROP TYPE IF EXISTS public.account_type;
CREATE TYPE public.account_type AS ENUM (
    'Admin', 
    'Client',
    'Employee');

-- Table structure for table 'classification'
CREATE TABLE public.classification (
classification_id INT GENERATED BY DEFAULT AS IDENTITY, 
classification_name CHARACTER VARYING NOT NULL,
CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character (4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric (9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)  
);

-- Create relationship between 'classification' and 'inventory' tables
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;


-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);


-- ================================================
-- Table structure for table 'favorites'
-- Allows users to save vehicles as favorites
-- ================================================
DROP TABLE IF EXISTS public.favorites;

CREATE TABLE public.favorites (
    favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    inv_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),

    -- Foreign keys
    CONSTRAINT fk_favorites_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_favorites_inventory
        FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Prevent the same user from favoriting the same vehicle twice
CREATE UNIQUE INDEX favorites_unique_user_vehicle
ON public.favorites (account_id, inv_id);

  -- Fix description for HM Hummer
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update image and thumbanil paths
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
